version: '3.8'

services:
  nats-server:
    image: nats:latest
    container_name: nats
    ports:
      #- "${NATS_PORT}:${NATS_PORT}"
      - 4222:4222
      - 8222:8222
    networks:
      - nats-net

networks:
  nats-net:
    driver: bridge
